### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by Sax-Yusuph** [yusukebe/sonik#3]
Hi, great work so far.
I played with the react example a bit, and it looks amazing. 

However,  when trying a ui library (radix) on the island component, I get a window is not defined error. And in some cases the server crashes. I know this is WIP, just wanted to put it to your notice. 
Thanks.

**Comment by yusukebe** [comment]
Hi @Sax-Yusuph !

Thank you for trying out Sonik and bringing up the issue. I haven't tried integrating a UI library with React yet, but your observation is very valuable. I'll work on finding a way to support them!

**Comment by yusukebe** [comment]
@Sax-Yusuph 

FYI, I can use the `@radix-ui/themes` with adding the following Vite settings:

```ts
export default defineConfig({
  ssr: {
    external: ['classnames']
  }
  // ...
})
```

**Comment by Sax-Yusuph** [comment]
Oh that's awesome... will check it out thanks
