### ISSUE TITLE
Use Tailwind just with @hono/jsx?

### ISSUE THREAD

**Issue by bruceharrison1984** [yusukebe/sonik#5]
I'm looking to use this lib with Tailwind, but can't seem to get it working without one of the additional JS frameworks. Pages render, but the Tailwind styles don't work.

Is there anyway to get this working just with Hono?

**Comment by bruceharrison1984** [comment]
I was able to get it working by creating the following:
```ts
// app/client.ts
import './style.css'
```
as well as adding the following to quiet the linter error:
```ts
// app/env.d.ts
interface ImportMeta {
  env: {
    PROD: string;
  };
}
```

**Comment by yusukebe** [comment]
Cool!
